### ISSUE TITLE
Trying to understand "useless" code

### ISSUE THREAD

**Issue by davidsneighbour** [appzcoder/30-seconds-of-php-code#51]
I am trying to understand the sense (strategy? meaning?) behind a function like the following:

```
function chunk($items, $size)
{
    return array_chunk($items, $size);
}
```

There is nothing to it, and only the array part of the function name is dropped. Is this something where all "30 seconds of ***" must have a `chunk` function or is it one of these "organically grown" functions that were not available in PHP before version X?

**Comment by pyrsmk** [comment]
It's surely useless... It should be dropped IMHO.
