### ISSUE TITLE
isContains pointless

### ISSUE THREAD

**Issue by paulcanning** [appzcoder/30-seconds-of-php-code#56]
Another pointless snippet; isContains.

It's wrapping a super basic function and offers nothing new.

**Comment by VincentAM** [comment]
I agree, and it's false, strpos return the position, not only true/false

![strpos_sandbox](https://user-images.githubusercontent.com/11472079/52722829-b63f6880-2fac-11e9-845a-c38a02294d53.PNG)

**Comment by paulcanning** [comment]
@sohelamin why has this been closed?
